### PR TITLE
Fixed compiler error under ghc-8.4

### PR DESCRIPTION
**Pull request by jchia**
Under ghc-8.4, (<>) is in Prelude

### CODE REVIEW

**Comment by liskin** [comment]
I'd prefer to do this without CPP, by using explicit imports (as opposed to explicit non-imports). Can you pls try to do that? (I don't have GHC 8.4 here so it'd take me a while to get to this.)

Also, if you need to do whitespace changes to unrelated code, do so in a separate commit, thanks!

**Comment by tkvogt** [comment]
It works for me. It is such a trivial change that you don't have to test it.

**Comment by liskin** [comment]
Oh, it's github's fault actually. Didn't send me an e-mail that @jchia pushed for the second time. :-(

**Comment by liskin** [comment]
Released v0.2.2 to Hackage. Thanks!

**Pull request merged**
